config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :reviews

root to: "reviews#top"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
    @review = Review.new
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
  	@review = Review.find(params[:id])
  end

  def update
   	@review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to review_path(@review.id)
    else
      render :edit
    end
  end

  def destroy
  	review = Review.find(params[:id])
  	review.destroy
  	redirect_to reviews_path
  end

  def create
  	@review = Review.new(review_params)
  	if @review.save
      redirect_to review_path(@review.id), notice: "Book was successfully created."
    else
      @reviews = Review.all
      render :index
    end
  end

  private
    def review_params
      params.require(:review).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KADAI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
<body>

  <h1>Editing Book</h1>

  <%= form_for(@review) do |f| %>
    <% if @review.errors.any? %>
      <div class="error">
        <% @review.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <%= form_for(@review) do |f| %>
    <p class="normal">Title</p>
    <%= f.text_field :title, class: "book_title" %>
    <p class ="normal">Body</p>
    <%= f.text_area :body, class: "book_body" %>
    <div class="create">
      <%= f.submit "Update Book" %>
    </div>
  <% end %>

  <div class="idou">
    <p> <%= link_to "Show", review_path(@review.id), class: "show_#{@review.id}" %>
        <span>|</span>
        <%= link_to "Back", reviews_path, class: "back" %>
    <p>
  </div>

</body>

app/views/reviews/index.html.erb
<body>

  <h1>Books</h1>

  <%= form_for(@review) do |f| %>
    <% if @review.errors.any? %>
      <div class="error">
        <% @review.errors.full_messages.each do |message| %>
          <p><%= message %></p>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <table class="clearfix">
    <tr class="column">
      <th>Title</th>
      <th>Body</th>
      <th></th>
    </tr>

    <% @reviews.each do |review| %>
        <tr>
        <td> <%= review.title %> </td>
        <td> <%= review.body %> </td>
        <td class="link"> <%= link_to "Show", review_path(review.id), class: "show_#{review.id}" %> </td>

        <td class="link"> <%= link_to "Edit", edit_review_path(review.id), class: "edit_#{review.id}" %> </td>

        <td class="link"> <%= link_to "Destroy", review_path(review.id), class: "destroy_#{review.id}", method: :delete, "data-confirm" => "Are you sure？" %> </td>
　　   </tr>
    <% end %>

  </table>

  <div class="new">
    <h2>New book</h2>
    <%= form_for(@review) do |f| %>
      <p class="normal">Title</p>
      <%= f.text_field :title, class: "book_title" %>
      <p class="normal">Body</p>
      <%= f.text_area :body, class: "book_body" %>

      <div class="create">
      	<%= f.submit "Create Book" %>
      </div>
    <% end %>
  </div>

</body>

app/views/reviews/top.html.erb
<body>
  <h1>ようこそBookersへ！</h1>
  <div id="shift">
    <p class="intro">
	  <Strong>Bookers</Strong>では、さまざまな書籍に関するあなたの意見や<br>
      印象を共有し交換することができます
    </p>
    <P class="top">
      <%= link_to "start", reviews_path %>
    </P>
  </div>
</body>